// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBAvCFJWz49jjXmWlg7oP35rpx0iY_0j8',
    appId: '1:164470656796:web:3c02d967f25c7faa5d34d9',
    messagingSenderId: '164470656796',
    projectId: 'mhike-f4190',
    authDomain: 'mhike-f4190.firebaseapp.com',
    storageBucket: 'mhike-f4190.firebasestorage.app',
    measurementId: 'G-N646ZBSDKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEfDaPp-k9IjaLOwz2AWZVuShCzWA5sAw',
    appId: '1:164470656796:android:493d7b0c72b7b44b5d34d9',
    messagingSenderId: '164470656796',
    projectId: 'mhike-f4190',
    storageBucket: 'mhike-f4190.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIRkcJyzLVUYnMYqyqheEuauY8M7x-JIM',
    appId: '1:164470656796:ios:84e8ad83aa3fead95d34d9',
    messagingSenderId: '164470656796',
    projectId: 'mhike-f4190',
    storageBucket: 'mhike-f4190.firebasestorage.app',
    iosBundleId: 'com.example.mhike',
  );
}
